namespace DBSchemaComparator.Domain.Models.Test
{
    public enum ObjectType
    {
        Table,
        Column,
        StoredProcedure,
        Index,
        ForeignKey,
        Check,
        DataType,
        IsNullable,
        IsIdentification,
        Function,
        Root,
        TablesTests,
        ColumnsTests,
        StoredProceduresTests,
        FunctionsTests,
        IndexTests,
        ViewsTests,
        View,
        IntegrityConstraintsTests,
        Script,
        PrimaryKeysTests,
        PrimaryKey,
        CheckTests,
        ForeignKeysTests,
        DatabaseCollation
    }
}
